# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nature Photography
email: vin.piotrowski@gmail.com
description: Join Vince Piotrowski and Sandra Mills as they trek through vast tracks of wilderness around Calgary, Alberta searching for birds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://birdnerds.ca/"

# Build settings
markdown: kramdown
